spring.application.name=account-service
server.port=8081

spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/ridelink_account}

jwt.secret=${JWT_SECRET:dev-only-change-me-please-use-env}
jwt.expiration-ms=${JWT_EXPIRATION_MS:3600000}
jwt.issuer=ridelink-account

internal.api-key=${INTERNAL_API_KEY:dev-internal-key}

springdoc.swagger-ui.path=/swagger-ui.html