spring.application.name=fare-payment-service
server.port=8084

spring.mongodb.uri=${MONGODB_URI}
spring.mongodb.database=ridelink_payment_db

# OpenAPI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operationsSorter=method

# JWT
jwt.secret=${JWT_SECRET}
jwt.issuer=${JWT_ISSUER:ridelink-account}