spring.application.name=fare-payment-service
server.port=8084

spring.mongodb.uri=mongodb+srv://ridelink_user:ADIT3130@cluster0.zztok57.mongodb.net/?appName=Cluster0
spring.mongodb.database=ridelink_payment_db